const
  FETCH_ITEMS = "FETCH_ITEMS",
  SET_ITEMS = "SET_ITEMS",
  ACTION_FAILED = "ACTION_FAILED",
  SET_LOADING_STATUS = "SET_LOADING_STATUS";

export default {
  SET_ITEMS,
  FETCH_ITEMS,
  ACTION_FAILED,
  SET_LOADING_STATUS
};
